# Classification models
1. logistic regression
2. naive bayes
3. decision tree
4. random forest
5. support vector machine
6. k-nearest neighbour

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

#NAIVE BAYES

In [11]:
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(data = np.c_[iris['data'], iris['target']],
                  columns=iris['feature_names'] + ['target'])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [8]:
x = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

In [10]:
acc = accuracy_score(y_test, y_pred)
c_m = confusion_matrix(y_test, y_pred)

print(f"accuracy: ",acc)
print(f"confusion matric: \n",c_m)

accuracy:  1.0
confusion matric: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


#DECISION TREE


In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [14]:
y_pred = model.predict(x_test)

In [15]:
acc = accuracy_score(y_test, y_pred)
c_m = confusion_matrix(y_test, y_pred)

print(f"accuracy: ",acc)
print(f"confusion matric: \n",c_m)

accuracy:  1.0
confusion matric: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


#RANDOM FOREST

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [19]:
y_pred = model.predict(x_test)

In [20]:
acc = accuracy_score(y_test, y_pred)
c_m = confusion_matrix(y_test, y_pred)

print(f"accuracy: ",acc)
print(f"confusion matric: \n",c_m)

accuracy:  1.0
confusion matric: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


#SUPPORT VECTOR MACHINE


In [23]:
from sklearn.svm import SVC

In [24]:
model = SVC()
model.fit(x_train, y_train)

SVC()

In [25]:
y_pred = model.predict(x_test)

In [26]:
acc = accuracy_score(y_test, y_pred)
c_m = confusion_matrix(y_test, y_pred)

print(f"accuracy: ",acc)
print(f"confusion matric: \n",c_m)

accuracy:  1.0
confusion matric: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


#K-NEAREST NEIGHBOUR


In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [30]:
y_pred = model.predict(x_test)

In [31]:
acc = accuracy_score(y_test, y_pred)
c_m = confusion_matrix(y_test, y_pred)

print(f"accuracy: ",acc)
print(f"confusion matric: \n",c_m)

accuracy:  1.0
confusion matric: 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
